steps:
  - label: ":golang: Test step"
    key: "gotest"
    commands:
      - "gotestsum --junitfile junit.xml ./..."
    artifact_paths: "junit.xml"
    plugins:
      # Run tests in Golang docker container
      - docker#v5.11.0:
          image: "packages.buildkite.com/flying-llamas-ltd/buildkite-example-docker-registry/golang-with-gotestsum:1.18.0"
      # Uploads test run output (JUnit XML format) to Buildkite Test Engine
      - test-collector#v1.10.2:
          # See .buildkite/hooks/post-command for analytics token fetching
          files: "junit.xml"
          format: "junit"
  - label: "Test results"
    key: "gotest-results"
    depends_on: "gotest"
    plugins:
      # Annotate build log with pretty test results
      - junit-annotate#v2.5.0:
          artifacts: "junit.xml"
  - label: ":golang: Build step"
    key: "gobuild"
    depends_on: "gotest"
    commands:
      - "cd hello"
      - "go build"
    artifact_paths: "hello/hello"
    plugins:
      - docker#v5.11.0:
          image: "packages.buildkite.com/flying-llamas-ltd/buildkite-example-docker-registry/golang-with-gotestsum:1.18.0"
  - label: ":name-badge: Name entry step"
    key: "name-entry"
    depends_on: "gobuild"
    block: "Enter name"
    prompt: "... and who's asking?"
    fields:
      - text: "Name argument to 'hello' command"
        key: "test-name-arg"
        default: "Luther Blissett"
        hint: "Used for testing the command output."
  - label: ":shipit: Binary test step"
    key: "binary-test"
    depends_on: "name-entry"
    command: "./test.sh"
