#!/bin/bash
set -euo pipefail

# Fetches the Buildkite Analytics Token from the Buildkite secrets store
# so the test-collector plugin can use it.
# See:
# https://buildkite.com/docs/pipelines/security/secrets/buildkite-secrets

# This only runs for the go test runner step
if [[ "$BUILDKITE_STEP_KEY" == "gotest" ]]; then
    export BUILDKITE_ANALYTICS_TOKEN=$(buildkite-agent secret get analytics_token)
fi
